# .gitlab-ci.yml corrigido para Bash & Blade
image: rust:latest

stages:
  - setup
  - build
  - test
  - lint

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  RUSTUP_HOME: $CI_PROJECT_DIR/.rustup

cache:
  key: ${CI_JOB_NAME}
  paths:
    - .cargo/bin
    - .cargo/registry
    - target/

before_script:
  - rustup default stable  # Primeiro definimos a toolchain padrão
  - rustup component add rustfmt clippy
  - cargo --version
  - rustc --version

setup:
  stage: setup
  script:
    - cargo fetch
  cache:
    policy: pull

build:
  stage: build
  script:
    - cargo build --verbose --release

unit_tests:
  stage: test
  script:
    - cargo test --verbose --lib

integration_tests:
  stage: test
  script:
    - cargo test --verbose --tests

lint:
  stage: lint
  script:
    - cargo fmt -- --check
    - cargo clippy -- -D warnings