[package]
name = "bash_and_blade"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "bash_and_blade"
path = "src/lib.rs"

[[bin]]
name = "bash-and-blade"
path = "src/main.rs"