[package]
name = "bash_and_blade"
version = "0.2.0-dev"
edition = "2024"

[dependencies]
chrono = "0.4"

[lib]
name = "bash_and_blade"
path = "src/lib.rs"

[[bin]]
name = "bash_and_blade"
path = "src/main.rs"